### ISSUE TITLE
Bad universal wheel on PyPI

### ISSUE THREAD

**Issue by FlorianVeaux** [micheles/decorator#101]
Hello,
I see you recently uploaded v5.0.x of the `decorator` library to PyPI which notably drops support for Python2.
Yet the wheel that was published is an universal wheel while it should be a pure python3 wheel instead.

Because of this `pip install decorator` now fails on python2 while it should install v4.4.2
https://pypi.org/project/decorator/#files

Would you mind to yank the latest release and upload a pure py3 wheel instead?

**Comment by mast** [comment]
I guess we created identical issues at the same time #102   =)
+1

**Comment by FlorianVeaux** [comment]
Closing this one in favor of #102
