### ISSUE TITLE
args tuple error in v5

### ISSUE THREAD

**Issue by bauman** [micheles/decorator#104]
I'm not sure if this is by design, but I have a lot of decorators that look like this

```python
@decorator
def wrap(func_, *args, **kwargs):
    if not args[-1]:
        new_args = list(args)
        new_args[-1] = ENVIRONMENT_DEPENDENT_VAR
        args = tuple(new_args)
    return func_(*args, **kwargs)

@wrap
def do_stuff(requiredvar, optionalvar=None):
    pass # real work
    return 

```

basically checking if a certain variable is set and, if not, setting it to some appropriate veriable depending on whatever situation.

In v4, when calling `do_stuff(some_var)`

the args value within `wrap` would be `(some_var, None)` 

in v5, 
the args value within `wrap` is now `(some_var, )`

Is this intentional to no longer supply a None (or whatever the function's default is) for named positional arguments?

**Comment by dschult** [comment]
This is causing many errors for the NetworkX test suite. The `(extra + args)` object is shorter than it used to be. 
line decorator.py:#214
```
    return caller(func, *(extras + args), **kw)
```

**Comment by bauman** [comment]
copied from #103 

I think v4 is _correct_ for the way python interprets the difference between positional args, named positional args, and keyword args

v5 looks like it lost introspection on the function it decorates and can no longer tell the difference.

If the decorated function uses a variable as a named positional variable, it isn't included in the kwargs dict for that function and preferably not for the decorator either. 

Current python below  shows that a named positional argument in a function definition does not fall down into the keyword arguments. 

```python
def test_behavior(*args, **kwargs):
    print(f"args: {args} \n kwargs:{kwargs}")

def test_behavior2(required, optional=None, **kwargs):
     print(f"req: {required} \noptional={optional} \nkwargs:{kwargs}")


test_behavior()
args: () 
 kwargs:{}
test_behavior("hi")
args: ('hi',) 
 kwargs:{}
test_behavior(named="hi")
args: () 
 kwargs:{'named': 'hi'}



test_behavior2("hi")
req: hi 
optional=None 
kwargs:{}
test_behavior2("hi", "world")
req: hi 
optional=world 
kwargs:{}
test_behavior2("hi", optional="world" )
req: hi 
optional=world 
kwargs:{}
test_behavior2("hi", optional="world", something_else="weird")
req: hi 
optional=world 
kwargs:{'something_else': 'weird'}
```

**Comment by dschult** [comment]
Yes -- version 5 loses the default values for the called function. (unless I'm using @decorator incorrectly)
```python
def tryme(index):
    @decorator.decorator
    def _tryme(func, *args, **kwargs):
        print(f"args: {args}, kwargs: {kwargs}")
        # we have no way to access the default values here...  They used to be in args
        return func(*args, **kwargs)
    return _tryme

@tryme(2)
def some_function(zeroth, first, second="some default")
    pass

some_function(0, 1, 2)
print()
some_function(0, 1)
```
Version 5 gives 
```
args: (0, 1, 2), kwargs: {}

args: (0, 1), kwargs: {}
```
Version 4 gives
```
args: (0, 1, 2), kwargs: {}

args: (0, 1, 'some_default'), kwargs: {}
```

**Comment by bauman** [comment]
> (unless I'm using @decorator incorrectly)

@dschult I can't speak for how you're _supposed_ to use this library, and don't fault the maintainer for making a breaking change across a major version.

However, I think it's _fair_ to request a feature where the decorator maintains the `(*args, **kwargs)` __exactly__ as they'd be passed to the called function, which is how v4 behaved.

**Comment by micheles** [comment]
I also think that the current behavior is wrong and I was not happy to change it (see my last comment in #39). But I am not sure it is fixable without going back to using "exec" and some people will protest anyway, because they want the opposite behavior :-(

**Comment by micheles** [comment]
> ```python
> def tryme(index):
>     @decorator.decorator
>     def _tryme(func, *args, **kwargs):
>         print(f"args: {args}, kwargs: {kwargs}")
>         # we have no way to access the default values here...  They used to be in args

You can access the default values with `func.__defaults__` or even with `inspect.signature(func).parameters`.

**Comment by micheles** [comment]
> I'm not sure if this is by design, but I have a lot of decorators that look like this
> 
> ```python
> @decorator
> def wrap(func_, *args, **kwargs):
>     if not args[-1]:
>         new_args = list(args)
>         new_args[-1] = ENVIRONMENT_DEPENDENT_VAR
>         args = tuple(new_args)
>     return func_(*args, **kwargs)]

A workaround would be to write ot as
```python
@decorator
def wrap(func_, *args, **kwargs):
    if func_.__defaults__ == (None,):
        new_args = list(args) + [ENVIRONMENT_DEPENDENT_VAR]
        args = tuple(new_args)
    return func_(*args, **kwargs)
```

**Comment by dschult** [comment]
Thanks @micheles for these helpful comments. I am disappointed (as you are) that this functionality is not preserved.

Can you easily come up with an idiom that converts from the new behavior to the old behavior? What would be problematic about something like:
```python
@decorator
def _my_decorator(func, *args, **kw):
    old_style_args = args + func.__defaults__[len(args) - len(inspect.signature(func).parameters):]
    code_that_uses_old_style_args
```

Thanks!

**Comment by micheles** [comment]
That should be more or less right if your functions have only simple parameters. In general, parameters can be of many kinds, see 
https://docs.python.org/3/library/inspect.html#inspect.Parameter.kind

**Comment by ahnitz** [comment]
@micheles I'll add my support that the change in behavior seems incorrect (i.e. it was previously correct).

**Comment by micheles** [comment]
I am back to the previous behavior now. Happy Easter!
