### ISSUE TITLE
__qualname__ shold not be set if not existing

### ISSUE THREAD

**Issue by petrutlucian94** [micheles/decorator#11]
At the moment, the __qualname__ attribute is set as None if the decorated function does not have this attribute. This can be considered unexpected behavior and can cause problems in some cases.

This attribute should either not be set if the decorated function does not have it, either use the __name__ value instead.

**Comment by micheles** [comment]
I have no problems in changing the behavior, but do you care to explain why it cause problems for you? The only case I can think of is in code that performs an `hasattr(func, '__qualname__')` to infer if we are using Python 2.X or Python 3.X

**Comment by petrutlucian94** [comment]
This is close to the issue I had. A profiling library used by the OpenStack projects was attempting to build function names using the qualname attribute, if set, without checking the Python version.

Although this should be fixed in that particular library, I thought that it might be a good idea to avoid this kind of situations in the future, preserving this aspect of the decorated function.

**Comment by micheles** [comment]
I have released version 4.0.1 that fixes the problem.

**Comment by petrutlucian94** [comment]
Thanks for fixing this so quickly.
