### ISSUE TITLE
pip install smbprotocol[kerberos] started failing all of sudden since april 4, 2021

### ISSUE THREAD

**Issue by saitrips** [micheles/decorator#111]
When I investigated the build error. I tracked it is failing to  install decorator dependency package.  I got around it by installing an older version decorator first.  we are using dotnet/core/aspnet:3.1 as our container base image.

pip install decorator==4.4.2

![image](https://user-images.githubusercontent.com/13564201/113887519-8efd1400-978f-11eb-8a38-40d9c52ddf4e.png)

**Comment by micheles** [comment]
Decorator 5 dropped support for Python 2.7. Using 4.4.2 is the correct solution as you found out.
