### ISSUE TITLE
Is it time to drop support for Python 3.5?

### ISSUE THREAD

**Issue by cclauss** [micheles/decorator#117]
https://devguide.python.org/#status-of-python-branches vs.
https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by micheles** [comment]
I know. When GitHub Actions will remove Python 3.5 and I will be unable to test the decorator module I will drop the support for it. For the moment it costs nothing to me to support Python 3.5.

**Comment by cclauss** [comment]
GitHub Actions will not remove 3.5...
They still support Python 3.0 https://github.com/actions/python-versions/blob/main/versions-manifest.json#L2081
