### ISSUE TITLE
Pip Install failing

### ISSUE THREAD

**Issue by sankhakarfa** [micheles/decorator#119]
Getting this error while installing decorator using python2 pip

Collecting decorator>=3.2.0 (from pycuda>=2019.1.1)
  Using cached https://files.pythonhosted.org/packages/71/bd/042e63027bea950da4e6f5545eb59b973868da854ab30a18128d3b884104/decorator-5.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-SbJ3it/decorator/setup.py", line 4, in <module>
        exec(open('src/decorator.py').read(), dic)  # extract the __version__
      File "<string>", line 162
        print('Error in generated code:', file=sys.stderr)
                                              ^
    SyntaxError: invalid syntax

**Comment by sankhakarfa** [comment]
Using 4.4.2 version as the new version is not working in python 2.7

**Comment by micheles** [comment]
It seems that pip is not working correctly. You have this line
```
Using cached https://files.pythonhosted.org/packages/71/bd/042e63027bea950da4e6f5545eb59b973868da854ab30a18128d3b884104/decorator-5.0.2.tar.gz
```
so it is trying to download the buggy version 5.0.2 even if I have "Yanked" it. So now I really deleted that release from PyPI.
In theory now
```
$ pip2 install decorator --no-cache-dir
```
should install version 4.4.2
