### ISSUE TITLE
Missing it tag(s)?

### ISSUE THREAD

**Issue by kloczek** [micheles/decorator#122]
According to https://pypi.org/project/decorator/ latest version of the decorator is 5.0.7 however I don't see version tag for that version in git repo.

**Comment by micheles** [comment]
I forgot that you need to do a  `git push --tags` for the tags to appear on GitHub. Now they are visible, thanks for noticing.

**Comment by kloczek** [comment]
Thank you :)

**Comment by kloczek** [comment]
Looks like tag for 5.1.0 is not pushed :)
