### ISSUE TITLE
AttributeError when decorating __setitem__, __delitem__

### ISSUE THREAD

**Issue by s1913388** [micheles/decorator#123]
```python
from collections import defaultdict
from decorator import decorator

@decorator
def notify(func, *args, **kw):
    result = func(*args, **kw)
    print("Changed")
    return result


class CustomDict(defaultdict):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    __setitem__ = notify(defaultdict.__setitem__)
    __delitem__ = notify(defaultdict.__delitem__)
```
Received following error.
```
AttributeError: 'wrapper_descriptor' object has no attribute '__module__'
```
Any resolution for this issue?

**Comment by micheles** [comment]
`defaultdict.__setitem__` is a C-function (more precisely a slow wrapper) and as such has no `__module__` attribute. The decorator module should be able to manage this case too, but it needs a fix.

**Comment by micheles** [comment]
Actually this looks impossible to solve, since builtin functions have no signature:
```python
 inspect.signature(dict.__getitem__)
*** ValueError: no signature found for builtin <method '__getitem__' of 'dict' objects>
```
Both ipython and pydoc fails in retrieving the signature, so it looks like I cannot do any better.

**Comment by micheles** [comment]
Fixed here: https://github.com/micheles/decorator/commit/dbb10360ec5e11126c6c3354038e1d41485c6323
You can download release 5.0.8 with the fix.
