### ISSUE TITLE
Something wrong with version `5.x`

### ISSUE THREAD

**Issue by mindflayer** [micheles/decorator#126]
Hi there,
I am the author of `mocket`. Its decorator is based on your amazing `decorator` module.

Days ago a `mocket` user opened an issue with an example similar to the following one:

```python
@mocketize
@patch("os.getcwd")
def test_patch(
    method_patch,
):
    method_patch.return_value = 'foo'
    assert os.getcwd() == "foo"
```

This example stops working when I `pip install decorator>=5`.

This was the error for him:

```python
Traceback (most recent call last):
  File "/Users/anas/Projects/project_name/.venv/lib/python3.7/site-packages/decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
  File "/Users/anas/Projects/project_name/.venv/lib/python3.7/site-packages/decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
  File "/Users/anas/.pyenv/versions/3.7.9/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/Users/anas/.pyenv/versions/3.7.9/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'method_patch'
```

And the same error happens when I try my example:

![Screenshot from 2021-05-21 10-37-16](https://user-images.githubusercontent.com/527325/119108527-92d3b580-ba20-11eb-9189-92254a1df148.png)

**Comment by micheles** [comment]
Can you send me a complete script showing the error? The snipped above misses the imports and I don't know what `patch` are you using (the one from unittest.mock? another one?) Version 5 is a major version, so something may break indeed.

**Comment by mindflayer** [comment]
Sure, here is what you need:

```shell
pip install mocket<3.9.41
```

```python
from unittest.mock import patch

from mocket import mocketize

@mocketize
@patch("os.getcwd")
def test_patch(
    method_patch,
):
    method_patch.return_value = 'foo'
    assert os.getcwd() == "foo"
```

**Comment by micheles** [comment]
I am looking at it. For the moment I suggest the following workaround:
```python
@patch("os.getcwd")
@mocketize
def test_patch...
```

**Comment by micheles** [comment]
As I suspected the error lies in `patch` which is changing the behavior of the function. Consider the following:
```python
@patch("os.getcwd")
def example(method_patch):
    print(method_patch)
    method_patch.return_value = 'foo'
    assert os.getcwd() == "foo"

>>> example()  # called with no arguments, a magicmock will be magically passed
<MagicMock name='getcwd' id='139852294688336'>
```
I have a fix but I am reluctant to apply it since it may hide errors. Here we discovered that `patch` is doing "dirty" things,
in particular it allows to call the `example` function without arguments even if its signature says that the argument `method_patch` is required. 

There is another workaround that you can try. I am going to open a PR on python-mocket with the workaround.

**Comment by mcepl** [comment]
> As I suspected the error lies in `patch` which is changing the behavior of the function. Consider the following:
> 
> ```python
> @patch("os.getcwd")
> def example(method_patch):
>     print(method_patch)
>     method_patch.return_value = 'foo'
>     assert os.getcwd() == "foo"
> 
> >>> example()  # called with no arguments, a magicmock will be magically passed
> <MagicMock name='getcwd' id='139852294688336'>
> ```
> 
> I have a fix for the decorator module but I am reluctant to apply it since it may hide errors. Here we discovered that `patch` is doing "dirty" things, in particular it allows to call the `example` function without arguments even if its signature says that the argument `method_patch` is required.
> 
> There is another workaround that you can try. Please apply to mocket.py the following patch:
> 
> ```
> $ git diff
> diff --git a/mocket/mocket.py b/mocket/mocket.py
> index a400e77..491c121 100644
> --- a/mocket/mocket.py
> +++ b/mocket/mocket.py
> @@ -627,7 +627,11 @@ class Mocketizer(object):
>                  t(*args, **kw)
>              return wrapper
>  
> -        return decorator.decorator(wrapper, test)
> +        if decorator.__version__ < '5':
> +            return decorator.decorate(test, wrapper)
> +        else:
> +            # fix https://github.com/mindflayer/python-mocket/issues/148
> +            return decorator.decorate(test, wrapper, kwsyntax=True)
> ```
> 
> This will fix this issue and will make `mocketize` to work as decorators created with `functools.wrapper`.

This doesn't seem to work right:
```
[   13s] _______________ ERROR collecting tests/main/test_http_gevent.py ________________
[   13s] tests/main/test_http_gevent.py:3: in <module>
[   13s]     from tests.main.test_http import HttpEntryTestCase
[   13s] <frozen importlib._bootstrap>:971: in _find_and_load
[   13s]     ???
[   13s] <frozen importlib._bootstrap>:955: in _find_and_load_unlocked
[   13s]     ???
[   13s] <frozen importlib._bootstrap>:665: in _load_unlocked
[   13s]     ???
[   13s] /usr/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:170: in exec_module
[   13s]     exec(co, module.__dict__)
[   13s] tests/main/test_http.py:31: in <module>
[   13s]     class TrueHttpEntryTestCase(HttpTestCase):
[   13s] tests/main/test_http.py:40: in TrueHttpEntryTestCase
[   13s]     @mocketize(truesocket_recording_dir=recording_directory)
[   13s] mocket/mocket.py:635: in wrap
[   13s]     return decorator.decorate(test, wrapper, kwsyntax=True)
[   13s] /usr/lib/python3.6/site-packages/decorator.py:216: in decorate
[   13s]     sig = inspect.signature(func)
[   13s] /usr/lib64/python3.6/inspect.py:3065: in signature
[   13s]     return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
[   13s] /usr/lib64/python3.6/inspect.py:2815: in from_callable
[   13s]     follow_wrapper_chains=follow_wrapped)
[   13s] /usr/lib64/python3.6/inspect.py:2193: in _signature_from_callable
[   13s]     raise TypeError('{!r} is not a callable object'.format(obj))
[   13s] E   TypeError: None is not a callable object
```
