### ISSUE TITLE
Brown bag Release 4.0.1 (readme missing from manifest)

### ISSUE THREAD

**Issue by phgross** [micheles/decorator#13]
In commit 24d5f1539f0d876e4871ecca4f671d0710ab35bf you moved README.rst to a different place. However, because MANIFEST.in was not updated to reflect the new path, the README.txt file was not included in the source distribution for the 4.0.1 release, and now setup.py fails when trying to generate the description.

```
Getting distribution for 'decorator'.
error: docs/README.rst: No such file or directory
An error occurred when trying to install decorator 4.0.1. Look above this message for any errors that were output by easy_install.
While:
   Updating test.
   Getting distribution for 'decorator'.
 Error: Couldn't install: decorator 4.0.1
 Attempt 1 of "bin/buildout -n -t 5" failed.
```

@micheles

**Comment by micheles** [comment]
I have fixed MANIFEST.in and release version 4.0.2. Please try again and let me know.

**Comment by phgross** [comment]
:+1: works well, thx!
