### ISSUE TITLE
pylint warning W1113: keyword-arg-before-vararg

### ISSUE THREAD

**Issue by jupe** [micheles/decorator#133]
I've simple decorator with decorator specific keyword argument, similar than in examples, like this:
```python
@decorator
def log(func, test=True, *args, **kwargs):
     ...
```

but pylint doesn't like keyword argument that is before `**kwargs` and causes warning like this: 

```
W1113: Keyword argument before variable positional arguments list in the definition of log function (keyword-arg-before-vararg)
```

What is proper way to use decorator specific keyword arguments with this library ?

**Comment by micheles** [comment]
Don't use pylint or find a way to disable that check. The signature `log(func, test=True, *args, **kwargs)` is valid in Python 3.
