### ISSUE TITLE
Regression in 5.1.0 - decorator.contextmanager no longer compat with contextlib.contextmanager

### ISSUE THREAD

**Issue by wimglenn** [micheles/decorator#136]
The [docs give this example](https://github.com/micheles/decorator/blob/master/docs/documentation.md#contextmanager) of `decorator.contextmanager` as a drop-in replacement ("usage is identical") for `contextlib.contextmanager`:

```
from decorator import contextmanager

@contextmanager
def before_after(before, after):
    print(before)
    yield
    print(after)

ba = before_after('BEFORE', 'AFTER')

@ba
def hello():
    print('hello')

hello()

```

Expected output (correct in `decorator < 5.1.0`, and same in stdlib contextmanager):

```
BEFORE
hello
AFTER
```

Actual output in 5.1.0:

```
('BEFORE', 'AFTER')
hello
{}

```

Don't see any API change mentioned in the [changelog](https://github.com/micheles/decorator/blob/master/CHANGES.md) so I think this may be a regression introduced in fixing https://github.com/micheles/decorator/issues/130

**Comment by micheles** [comment]
This is fixed in master: https://github.com/micheles/decorator/commit/baf129705a56ead40a71b1813003439e06fd1538

**Comment by wimglenn** [comment]
@micheles Thanks, would you mind to publish a release please?

**Comment by micheles** [comment]
I am going to publish release 5.1.1 today.
