### ISSUE TITLE
memoize decorator example has cache leak when used on an instance

### ISSUE THREAD

**Issue by rbu** [micheles/decorator#14]
The memoize decorator as shown on https://pythonhosted.org/decorator/documentation.html#the-solution will cause a memory leak when decorating an ```instancemethod```, as the instance (self) is considered part of the cache key and cached results are not cleaned up as the instance is deleted. In fact, the instance is never deleted as the cache key still holds a reference to it.

While this does not necessarily need fixing (as it's just an example), there should be a big warning on the code. Or rather, maybe you can come up with a better example that can be implemented without such issues. The decorator as-is is currently copied to several projects or used as a base for extensions. See https://www.google.com/search?q="frozenset+is+used+to+ensure+hashability"

**Comment by micheles** [comment]
I would not call this a memory leak. It is intended behavior, the cache is keeping references as it should. I did not want to give a complex example with weak references. Still a warning for naive programmers with wrong expectations may be in order...

**Comment by rbu** [comment]
I understand the implementation is rather naive and if you look closely, it's obvious why you made these choices. I'm trying to point out that there are ways that will come to haunt you if you use this in production. Consider the following example:
```
class Something(object):
    @memoize
    def expensive_object(self):
        return generate_expensive_object()
```

Reading this code (without knowing what memoize does), I would expect that the expensive object is cleaned up after a "Something" object goes out of scope. But it does not.
```
a = Something().expensive_object()
b = Something().expensive_object()
c = Something().expensive_object()

del a
del b
del c
```

Now there's three expensive objects and three Something objects still in existence.
