### ISSUE TITLE
Confusion about license using

### ISSUE THREAD

**Issue by Ashley123456789** [micheles/decorator#152]
When I **import** decorator as a third-party dependency, 

- Should I comply with the LICENSE.txt (i.e., BSD 2-Clause)? Is the **import** action considered as **Redistribution and use** in the LICENSE.txt?
- Do I need to pay attention to **license compatibility**, i.e., can I claim a  **less strict license** than BSD 2-Clause for my projects?

**Comment by micheles** [comment]
The BSD license is non-viral, so you can import decorator and use your own different license.
