### ISSUE TITLE
Unable to pull 4.4.2 from the repo only pulls in 4.2.1

### ISSUE THREAD

**Issue by crookedmosquito** [micheles/decorator#156]
Having an issue pulling in the new version from the repo.  How can I get it to pull in properly, not able to kick off a PowerVC install due to it.

**Comment by micheles** [comment]
Not sure what you mean. The repo has a tag 4.4.2 so you should be able to download it. Also PyPI has version 4.4.2 available: https://pypi.org/project/decorator/4.4.2/
