### ISSUE TITLE
Erroneous `%` ?

### ISSUE THREAD

**Issue by lucascolley** [micheles/decorator#164]
Should the double `%` on line 445 be a single `%` (like elsewhere in the file), or is there some string syntax we are missing? Discovered in https://github.com/scipy/scipy/pull/21029#discussion_r1650191130.

https://github.com/micheles/decorator/blob/def9f604637e1084a34f8667cb26e104a2d62aa2/src/decorator.py#L444-L448

**Comment by micheles** [comment]
The double `%%` is not an error it is the standard way to escape the `%` character. So I guess it is a  string syntax you are missing ;-)

**Comment by lucascolley** [comment]
Ah, I see what it is doing now 👍 I was aware that it was escaping a `%` but didn't look closely enough at the 2-stage replacement going on. Thanks!
