### ISSUE TITLE
Tarball on PyPI contains src/tests/x.py which is not compatible with Py3

### ISSUE THREAD

**Issue by jelly** [micheles/decorator#21]
The tarball which I use to package decorator in Arch Linux has the file x.py in it (which can not be found in the Git repo)

The file itself is not compatible with Python 3, which makes python3 setup.py test fail.
I've created a patch for it in our [svn repo](https://projects.archlinux.org/svntogit/community.git/tree/trunk/print_unittest.patch?h=packages/python-decorator) but I rather see a fix in the tarball (so I don't have to patch it all the time)

Thanks!

**Comment by micheles** [comment]
The file entered accidentally and has been removed in version 4.0.6
