### ISSUE TITLE
kwargs is empty with decorator

### ISSUE THREAD

**Issue by lichen2013** [micheles/decorator#22]
Python : 2.7,  decorator (4.0.4)

Test with the following code:

    import decorator

    @decorator.decorator
    def test_decorator(f, *args, **kwargs):
        print('check args:')
        print(args)
        print('check kwargs')
        print(kwargs)
        return f(*args, **kwargs)

    class TestObject(object):

        @test_decorator
        def test(self, x, y, z):
            return x + y + z

    test = TestObject()
    test.test(x=2,y=2,z=4)

The output is:

    check args:
    (<__main__.TestObject object at 0x7f33a0b4ec50>, 2, 2, 4)
    check kwargs
    {}

**Comment by micheles** [comment]
This is absolutely correct. Your function (i.e. `test(self, x, y, z)`) has positional arguments `x`, `y`, `z` and has no keyword arguments. You probably misunderstand how Python argument passing works.
`test.test(x=2,y=2,z=4)` is passing positional arguments, not keyword arguments.

**Comment by lichen2013** [comment]
But if I create the decorator with out @decorator.decorator, it will return exactly what I want:

    def test_decorator_raw(f):
        def _decorator_raw(*args, **kwargs):
            print('check args:')
            print(args)
            print('check kwargs')
            print(kwargs)
            return f(*args, **kwargs)


class TestObject(object):

        @test_decorator_raw
        def test_raw(self, x, y, z):
            return x + y +z

    test = TestObject()
    test.test_raw(x=2,y=2,z=4)

The output is:

check args:
(<__main__.TestObject object at 0x7f9b3c2a6cd0>,)
check kwargs
{'y': 2, 'x': 2, 'z': 4}

    return _decorator_raw

**Comment by micheles** [comment]
Then use `test_decorator_raw`, but it is not preserving the signature, so it wrong for the goals of the decorator module.
