### ISSUE TITLE
Newline insertion in FunctionMaker.make

### ISSUE THREAD

**Issue by azjps** [micheles/decorator#23]
Hi, I was wondering what the reason was behind removing the append of the newline in [this commit](https://github.com/micheles/decorator/commit/a26c55c0d527e1b09b996e29f9d9d816d085addd#diff-f8677e3ea7b2e149185e885e191e6ffe). As far as I can tell, without a trailing newline python 2.7.x will raise a `SyntaxError: unexpected EOF while parsing` for `compile("def foo(): return bar", ..)` (and since its a SyntaxError, it can be pretty difficult to trace with the pdb family). Thanks

**Comment by micheles** [comment]
Are you sure you are using Python 2.7? That newline was removed because needed in Python versions < 2.6 and I have dropped support for such versions in decorator 4.0.

For me it is working even without newline:

```python
>>> dic = {}
>>> execute('def f(): pass', dic)
>>> dic['f']
<function f at 0x7f675bd9a758>
```

**Comment by micheles** [comment]
Anyway, I have restored the newline, since it is not a big effort on my part. Please upgrade to release 4.0.7

**Comment by azjps** [comment]
Thanks again. This error that was coming up for me was [over here](https://github.com/micheles/decorator/blob/master/src/decorator.py#L190):

```python
Python 2.7.6 (default, Jun  9 2015, 02:14:28) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> compile('def f(): pass', '', 'single')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "", line 1
    def f(): pass
                ^
SyntaxError: unexpected EOF while parsing
```
