### ISSUE TITLE
No files uploaded to PyPI for 4.0.7

### ISSUE THREAD

**Issue by The-Compiler** [micheles/decorator#25]
[On PyPI](https://pypi.python.org/pypi/decorator/4.0.7) it seems the 4.0.7 release has nothing uploaded, so installing it fails:

```
$ pip install decorator==4.0.7
Collecting decorator==4.0.7
  Could not find a version that satisfies the requirement decorator==4.0.7 (from versions: 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.2, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.6)
No matching distribution found for decorator==4.0.7
```

**Comment by micheles** [comment]
It seems that something went wrong with PyPI. I have uploaded another file called decorator-4.0.8-py2.py3-none-any.whl which is identical to 4.0.7.

**Comment by brbsix** [comment]
Just a FYI, `pip list --user --outdated` is now printing the following despite no update being available:

> `decorator (4.0.7) - Latest: 4.0.8 [wheel]`
