### ISSUE TITLE
Include "argument-resolving decorator" into decorator package ?

### ISSUE THREAD

**Issue by pakal** [micheles/decorator#33]
I've developed a handy utility which looks like @decorator, but pre-resolves arguments before passing them to the wrapper function (using https://docs.python.org/2/library/inspect.html#inspect.getcallargs).

It's very useful when you need to decorate many functions, without knowing it advanced if they'll be passed arguments by position (<_args>) or by keywords (<_*kwargs>). Since incoming arguments are normalized in a simple dict, you can inspect and modify them freely. 

I used it to automatically inject or commit/rollback SQL sessions which travelled through program, for example.

Below is an example of use.

Would you be OK for me to prepare a pull request including that utility next to the standard "decorator".

```
        @resolving_decorator
        def inject_session(func, **all_kwargs):
            if not all_kwargs["session"]:
                all_kwargs["session"] = "<SESSION>"
            return func(**all_kwargs)

        @inject_session
        def myfunc(session):
            return session

        assert myfunc(None) == myfunc(session=None) == "<SESSION>"
        assert myfunc("<stuff>") == myfunc(session="<stuff>") == "<stuff>"
```

**Comment by micheles** [comment]
You should make your case better, I am not understanding what you are proposing. The decorator module has never been a collection of useful decorators, so it is really hard to have something added to it. Not to see that any extension is out of question, but you should convince me that this is general enough to be included.

**Comment by pakal** [comment]
Actually if I see well the "resolving_decorator" included in that package, it's because imho it's just a variant of the "decorator.decorator" utility. 

Below is an excerpt from the decorator documentation. 

```
>>> @decorator
... def trace(f, *args, **kw):
... kwstr = ', '.join('%r: %r' % (k, kw[k]) for k in sorted(kw))
... print("calling %s with args %s, {%s}" % (f.__name__, args, kwstr))
... return f(*args, **kw)
```

As you see, when the decorated function get called at runtime, all arguments are passed as standard "*args, **kw" pair. So inside this "trace" decorator, it's complicated to extract, for example, an argument which would be an SQL session, because one doesn't know if it's in "args" (passed by position) or "kwargs" (passed by keyword).

The "resolving_decorator" would allow "trace" to receive a single "**all_kwargs" data set, with all arguments already bound to their final "local variable" name. Thus "trace" could simply do all_kwargs.get("sql_session"), and fiddle with this pre-resolved parameter. The only constraint would be, of course, that all decorated functions which want to have sql session handling, expose a "sql_session" argument in their signature.
