### ISSUE TITLE
nicer multiple decorator support

### ISSUE THREAD

**Issue by tolomea** [micheles/decorator#40]
I had a suggestion and wasn't sure where to put it, the basic idea is could the decorate function support multiple decorators in a single call so that:

    def my_decorator(func):
        return decorate(decorate(func, _caller), _precondition_caller)

could be rewritten as:

    def my_decorator(func):
        return decorate(func, _precondition_caller, _caller)

Maybe I'm just approaching decorator composition wrong, if so I'd love to see an alternative way.

**Comment by tolomea** [comment]
So the precondition is usable by itself, so I also have this:

    def precondition_decorator(func):
        return decorate(func, _precondition_caller)

Which I realize now allows this slightly tidier version

    def my_decorator(func):
        return precondition_decorator(decorate(func, _caller))

**Comment by micheles** [comment]
Closing since this is not an issue.

**Comment by tolomea** [comment]
@micheles is there somewhere else I should put it?

**Comment by micheles** [comment]
No, it is simply that I have no interest in making the syntax for composing decorators easier. It is best not to stack together too many levels of decorators.
