### ISSUE TITLE
Question concerning decorators with arguments

### ISSUE THREAD

**Issue by neimad1985** [micheles/decorator#44]
First thanks for the great work.

I've been reading your whole documentation and I am certainly missing the point, I am struggling with a syntax issue, cannot find the proper one.

Suppose I want to do the following dumb thing:

```python

import decorator

def printer(text):
    def _printer(func, *args, **kwargs):
        print(text)
        func(*args, **kwargs)
    return decorator.decorator(_printer)

@printer("Hello")
def world():
    print("World")

```
When executing, I get the following result:
```python
>>>world()
Hello
World
```
And that's totally fine !

Suppose now that I want my text to be optional. To do so I give a default value of `None` to the `text` parameter, check whether there is something to print or not in my `_printer` function and omit the argument when decorating. Resulting in the following code: 

```python
import decorator

def printer(text=None):
    def _printer(func, *args, **kwargs):
        if text:
            print(text)
        func(*args, **kwargs)
    return decorator.decorator(_printer)

@printer()
def world():
    print("World")
```

Execution is now:
```python
>>>world()
World
```

And once again that's fine but a detail bothers me, I am forced to write `@printer()` instead of `@printer` which I would prefer. But I cannot do so because if I do this leads to the following error:

```python
>>>world()
Traceback (most recent call last):
  File "toto.py", line 14, in <module>
    world()
TypeError: _printer() missing 1 required positional argument: 'func'
```

I have based my code on your `blocking` example in the documentation but that last detail beats me.
Is there a way to modify this code to achieve what I want or must I stay with the `@printer()` syntax ?
Thanks very much.

Neimad

**Comment by micheles** [comment]
Yes, there is. Rename your printer to _printer and then define printer =
_printer(). That's easy and clean, isn't it?

**Comment by neimad1985** [comment]
Hi, thanks for the quick reply !
I am not sure I understood your answer correctly. Or maybe it did not explain well enough what I want to achieve. With this optional argument I want to able to either use the decorator as `@printer` or `@printer("some string")`.

I adapted my code following your remark (I also renamed the inner `_printer` function to `inner_printer` for clarity's sake):
```python
import decorator

def _printer(text=None):
    def _inner_printer(func, *args, **kwargs):
        if text:
            print(text)
        func(*args, **kwargs)
    return decorator.decorator(_inner_printer)
printer=_printer()

@printer
def world():
    print("World")

@printer("Goodbye")
def universe():
    print("Universe")
```

The thing is that the function `world` gets decorated correctly but `universe` breaks the interpreter at definition time with the following error.

```python
Traceback (most recent call last):
  File "toto.py", line 15, in <module>
    @printer("Goodbye")
  File "<decorator-gen-1>", line 2, in _inner_printer
  File ".../lib64/python3.4/site-packages/decorator.py", line 240, in decorate
    evaldict, __wrapped__=func)
  File ".../lib64/python3.4/site-packages/decorator.py", line 215, in create
    name, rest = obj.strip().split('(', 1)
ValueError: need more than 1 value to unpack
```

Did I misunderstood your solution ? Could you correct my code ?

**Comment by linar-jether** [comment]
Stumbled on using optional decorator arguments, and found no docs on this.., came up with this solution:

*Note that this works for optional arguments, but limits you to use kwargs only.

```python
import decorator

def printer(_func=None, text='blah'):

    def _printer(func, *args, **kwargs):
        if text:
            print(text)
        func(*args, **kwargs)

    if _func:
        return decorator.decorate(_func, _printer)

    return decorator.decorator(_printer)

@printer
def world():
    print("World")

@printer(text='Hello')
def hello():
    print("World")

world()
hello()
```

I suggest adding a section on optional arguments to the docs.

**Comment by micheles** [comment]
This is a creative solution that works. Still, I do not like the whole idea, too much magic. What's wrong with having two parenthesis at the end of the decorator? Using `printer()` to me looks a lot clearer.

**Comment by neimad1985** [comment]
I agree with the "not too much magic" statement. I will use empty parenthesis though but thanks for the proposal.
I just asked this question in the first place in case i had missed something about how to use decorators. It finally seems that this is not a lack of knowledge but just some kind of edge case. Thanks for your time guys. For me, the ticket can be closed.

**Comment by micheles** [comment]
Since PEP 557 has been accepted (https://www.python.org/dev/peps/pep-0557) I have given up. If Guido thinks that it is fine to drop the parenthesis in a decorator factory, then it is fine. Starting from today (release 4.2.0) the following code is valid and does what you want:

```python
@decorator.decorator
def printer(func, text='hello', *args, **kwargs):
    print(text)
    return func(*args, **kwargs)

@printer
def world():
    print("World")
```
