### ISSUE TITLE
The documentation of this library is not very accessible 

### ISSUE THREAD

**Issue by amirma** [micheles/decorator#50]
I'm opening this as an issue because it is hindrance to it's usability. Even thought there are plenty of examples and explanation, the documentation is ineffective, in my subjective opinion. As a user I want to see/access the library API as fast as possible to see if it does what I need,  without having to scan through _Introduction, What’s New in version 4, Usefulness of decorators, Definitions, Statement of the problem and The solution._
Suggestions:
- Put few simple examples on the README page showing the salient properties of the library.
- Put the gist of the functionality in a separate section at the top of the documentation.

**Comment by micheles** [comment]
I would not change the documentation as it is, instead it could make sense to add a section "For the impatient" to the README, http://decorator.readthedocs.io/en/latest/README.html
It could contain this example:
```python
# an example of how to define a family of decorators warning in the log file if an operation is too slow
from decorator import decorator

@decorator
def warn_slow(func, timelimit=60, *args, **kw):
    t0 = time.time()
    result = func(*args, **kw)
    dt = time.time() - t0
    if dt > timelimit:
        logging.warn('%s took %d seconds', func.__name__, dt)
    else:
        logging.info('%s took %d seconds', func.__name__, dt)
    return result

@warn_slow  # warn if it takes more than 1 minute
def preprocess_input_files(input_dir):
    ...

@warn_slow(timelimit=600)  # warn if it takes more than 10 minutes
def run_full_calculation(tempdir, outdir):
    ...
```
What do you think?

**Comment by amirma** [comment]
Perfect. How about putting this on  README.md as well, so as soon as people land on the github page they see it?

**Comment by micheles** [comment]
Done!
