### ISSUE TITLE
Fully signature preserving equivalent of functools.wraps

### ISSUE THREAD

**Issue by shoyer** [micheles/decorator#54]
On Python 3, `functools.wraps` nominally preserves function signatures, e.g.,
```python
import functools

def original(x):
    return x

@functools.wraps(original)
def wrapper(*args, **kwargs):
    return original(*args, **kwargs)
```
The function has the right associated signature object (so introspection works properly) but abstraction is still a little leaky, e.g., for handling invalid function arguments:
```
In [11]: wrapper(y=1)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-1e0b778ae20b> in <module>()
----> 1 wrapper(y=1)

<ipython-input-4-878d38897098> in wrapper(*args, **kwargs)
      6 @functools.wraps(original)
      7 def wrapper(*args, **kwargs):
----> 8     return original(*args, **kwargs)

TypeError: original() got an unexpected keyword argument 'y'
```

I think the decorator library can produce fully compatible function signatures, but the interface is a little different: 
```python
@functools.partial(decorate, original)
def wrapper(original, *args, **kwargs):
    return original(*args, **kwargs)
```
In particular, it's awkward that I need to include the original function in the wrapper signature (e.g., `def wrapper(original, *args, **kwargs)` rather than `def wrapper(*args, **kwargs)` .

Is there an easy way to write a drop-in replacement for `functools.wraps` with the decorator library?

**Comment by micheles** [comment]
So you would like a `decorator.wraps` function which is a fully working replacement of `functools.wraps`?

```python
@decorator.wraps(original)
def wrapper(*args, **kwargs):
    return original(*args, **kwargs)
```
Perhaps it is possible, but I will have to think about that. I will keep you posted when I will have time to work on that. I actually like the idea, if it can be implemented.

**Comment by shoyer** [comment]
> So you would like a decorator.wraps function which is a fully working replacement of functools.wraps?

Yes, this is what I had in mind. We're contemplating using something this for NumPy (but not yet sure it's worth the complexity/run-time of dynamic code generation): http://www.numpy.org/neps/nep-0018-array-function-protocol.html#changes-within-numpy-functions

**Comment by micheles** [comment]
Well, both scipy and ipython as already using the decorator module as a dependency. In the NEP that you pointed out, there is an `array_function_dispatch`; if this is the only function of such a type you can just define it without using `functools.wraps` but with `decorator.decorator`, no?
You should also measure potential slowdowns due to the decoration, but I guess you have a performance regression suite just for that.

**Comment by shoyer** [comment]
> if this is the only function of such a type you can just define it without using functools.wraps but with decorator.decorator, no?

This is probably true, though I have a slight preference for the `functools.wraps` API. Maybe because I've gone through the trouble of understanding how normal decorators work, I'd rather not figure how the `decorator.decorator` abstraction works.

> You should also measure potential slowdowns due to the decoration, but I guess you have a performance regression suite just for that.

Yes, would definitely be part of the plan before adopting this.

**Comment by micheles** [comment]
> Maybe because I've gone through the trouble of understanding how normal decorators work, I'd rather not figure how the decorator.decorator abstraction works.

Yeah, but take into account that even if I will be able implement `decorator.wraps`, it will be a lie: it will look like the standard library utility, but it will work according to the `decorator.decorator` logic inside.

**Comment by micheles** [comment]
```python
def wraps(func):
    """
    :returns: a decorator for a wrapper function similar to functools.wraps
    """
    return lambda wrapper: decorate(func, lambda f, *a, **k: wrapper(*a, **k))
```
should act as a replacement of `functools.wrapper`. However, having thought about that, I will not include this in the decorator library. The point of my library is to make decorator easier, not more perverse. You should marry the decorator library and write your `array_function_dispatch` somewhat like this, with two levels of nesting less:
```python
@decorator.decorator
def array_function_dispatch(func, dispatcher=None, *args, **kwargs):
    """Wrap a function for dispatch with the __array_function__ protocol."""
    relevant_arguments = dispatcher(*args, **kwargs)
    success, value = try_array_function_override(
        new_func, relevant_arguments, args, kwargs)
    if success:
        return value
    return func(*args, **kwargs)
```

**Comment by shoyer** [comment]
> You should marry the decorator library and write your array_function_dispatch somewhat like this, with two levels of nesting less:

How would I get access to `new_func` in this example? (I agree that this is a somewhat unusual use-case.)

**Comment by micheles** [comment]
Ops, I missed that. In your original code you are calling new_func from inside its own definition?

```python
        def new_func(*args, **kwargs):
            relevant_arguments = dispatcher(*args, **kwargs)
            success, value = try_array_function_override(
                new_func, relevant_arguments, args, kwargs)
            if success:
                return value
            return func(*args, **kwargs)
```
Then I should read the NEP and understand the context ,first ;-) But now I am leaving for work, I will come back to this later on.
