### ISSUE TITLE
docs: first paragraph in first section ("introduction") section describe what this is/does

### ISSUE THREAD

**Issue by jmtd** [micheles/decorator#62]
I read somewhere today that ["In regards to PyPI, the "decorator" package is ~300 lines in total, and is one of the top most downloaded packages from pypi."](https://lwn.net/Articles/777407/). So I was curious and set off to read up on what the library is and what it does. 

Your README.rst does not explain what this library does, it just explains how to install it, or run the test suite, etc. The "For the impatient" is the closest to explaining what this does, by providing an example of using it for something. So it might be possible to extract what it does from that context, although I couldn't on first attempt.

Following the link to the full docs, https://decorator.readthedocs.io/en/latest/, Nothing on the front page explains what this is or does, but fair enough, it's just a ToC. However, the "introduction" section does not explain what this or does, either. The next section, "Whats new", is not relevant if you don't know what it is or does (yet), and the section after that, "Usefulness of decorators", seems to explain *why* the libraries does what it does, without explaining *what* it does.

I'm not trying to be too pedantic here. I've written a lot of Python, although I do not consider myself to be a Python programmer, in particular; and I suspect I've *used* decorators and probably even this library before (by virtue of hacking on something that used it). But despite that I genuinely do not know what this library does despite having read all of the above.

**Comment by micheles** [comment]
I am not sure what your point is. People in the past complained that the documentation was too long and I added the section for the impatient. The goal of the decorator module is to make it easy to define signature-preserving decorators. If you want to understand why this is important or you need to be already convinced or you need to read the 30+ pages of documentation I wrote.
