### ISSUE TITLE
Looks like it works on staticmethods  in python3.7

### ISSUE THREAD

**Issue by yjqiang** [micheles/decorator#65]
> In Python 3.5, many such limitations have been removed, but I still think that it is cleaner and safer to decorate only functions. If you want to decorate things like classmethods/staticmethods and general callables - which I will never support in the decorator module - I suggest you to look at the wrapt project by Graeme Dumpleton.

```py
from decorator import decorator
import asyncio
import time


@decorator
async def log_start_stop(func, *args, **kwargs):
    t0 = int(time.time())
    print(t0, f'core={func}, args={args},kwargs={kwargs}')
    result = await func(*args, **kwargs)
    t1 = int(time.time())
    print(t1, f'result={result}')


class A:
    @staticmethod
    @log_start_stop
    async def make_task(n):
        for i in range(n):
            await asyncio.sleep(1)
        return 100


a = A()
print(a)
loop = asyncio.get_event_loop()
try:
    loop.run_until_complete(A.make_task(5))
finally:
    loop.run_until_complete(loop.shutdown_asyncgens())
    loop.close()

```

**Comment by micheles** [comment]
The trick with staticmethod/classmethod is that the decorato module works only if you use the right order, which is the one you are using:
```
    @log_start_stop
    @staticmethod
    async def make_task(n):
```
For me this is a non-problem, of course the right order if the first one, because the decorator has to be applied to the function not to the staticmethod. With wrapt it would work in both orders.

**Comment by yjqiang** [comment]
> The trick with staticmethod/classmethod is that the decorator module works only if you use the right order, which is the one you are using. The opposite order will not work:
> ```python
>     @log_start_stop
>     @staticmethod
>     async def make_task(n):
> ```
> For me this is a non-problem, of course the right order if the first one, because the decorator has to be applied to the function not to the staticmethod. With wrapt it would work in both orders.

But it doesn't support coroutine.😢

**Comment by micheles** [comment]
I am right in understanding that you are happy with the current behavior and I can close issue?
If you have a problem please be more explicit.

**Comment by yjqiang** [comment]
> I am right in understanding that you are happy with the current behavior and I can close issue?
> If you have a problem please be more explicit.

Yeah, you can close this. But would you like to add something about this to documentation?

**Comment by micheles** [comment]
I will change `it is cleaner and safer to decorate only functions` -> `it is cleaner and safer to decorate only functions and coroutines`.

**Comment by yjqiang** [comment]
How about change `If you want to decorate things like classmethods/staticmethods and general callables - which I will never support in the decorator module - I suggest you to look at the wrapt project by Graeme Dumpleton.` to `If you want to decorate things like classmethods/staticmethods and general callables - which I will never support in the decorator module - I suggest you to look at the wrapt project by Graeme Dumpleton. But you can use the decorator module on these things carefully right now and it should work.`?

**Comment by micheles** [comment]
The documentation is correct, it is saying that you cannot decorate a staticmethod, meaning that `dec(staticmethod(func_or_coro))` is not working. It is implicit that
`staticmethod(dec(func_or_coro))` works since there is nothing strange there.

**Comment by yjqiang** [comment]
> The documentation is correct, it is saying that you cannot decorate a staticmethod, meaning that `dec(staticmethod(func_or_coro))` is not working. It is implicit that
> `staticmethod(dec(func_or_coro))` works since there is nothing strange there.

Got it. Sorry for my poor English, I misunderstood the documentation.
