### ISSUE TITLE
Description could be “decorator  for Humans”~

### ISSUE THREAD

**Issue by leafonsword** [micheles/decorator#68]
Python has many "XX  for Humans"  third-party libs, for example-- Python HTTP Requests for Humans, SQL for Humans;

Your decorator is an awesome and easy to use lib compared to Python official decorator,  why not modify Description to “decorator  for Humans” ？

**Comment by micheles** [comment]
You are the second person making the same suggestion. I will think about it!

**Comment by leafonsword** [comment]
@micheles 
One more reason for modifying description is: your decorator keyword is submerged by Python's official  decorator keyword , people search decorator in google or github couldn't get your decorator's speciality from first galance; 

While a “decorator for Humans” description could let people get the core speciality immediately~

**Comment by mrmachine** [comment]
Definitely, I just had trouble googling the docs for this module.

**Comment by micheles** [comment]
Done
