### ISSUE TITLE
__qualname__ not updated

### ISSUE THREAD

**Issue by RazerM** [micheles/decorator#7]
[`functools.update_wrapper`](https://hg.python.org/cpython/file/3.4/Lib/functools.py) sets `wrapper.__qualname__` to `wrapped.__qualname__`, is there a reason that `decorator.decorator` doesn't do the same?

I tried searching for a reason this is the case, but came up blank.

**Comment by micheles** [comment]
The reason is quite simple: when the decorator was first written, the `__qualname__` attribute did not exist. It is a "recent" invention of Python. I will add that attribute in the next release.
