### ISSUE TITLE
PyPI page shows raw ReStructuredText source

### ISSUE THREAD

**Issue by mgedmin** [micheles/decorator#72]
Currently https://pypi.org/project/decorator/ shows raw ReStructuredText and looks like this:

![Ekrano nuotrauka iš 2019-09-26 16-02-59](https://user-images.githubusercontent.com/159967/65690178-2780e700-e077-11e9-9603-e946b1c2be4e.png)

This is typically caused by some ReST error, although I'm currently having trouble seeing what it might be.

**Comment by mgedmin** [comment]
It might be that the wheel file you've uploaded to PyPI was built with an older version of wheel and lacks some metadata, or maybe the version of twine you used for the upload was too old and didn't submit the right metadata?

**Comment by altendky** [comment]
I have seen this in various situations without ever fully identifying why the supposed default (I think that's indicated somewhere) isn't always used.  It can be addressed explicitly such as:

https://github.com/altendky/exttr/blob/60aa5d6e9f04631b8e86552620f2d9cd2a0a3a04/setup.py#L12
```python3
long_description_content_type='text/x-rst',
```

**Comment by mgedmin** [comment]
Or it may be a ReST syntax error after all.  If I run twine check on the files downloaded from PyPI, I get errors:

```
twine check decorator-4.4.0.tar.gz 
Checking distribution /home/mg/Atsiuntimai/decorator-4.4.0.tar.gz: warning: `long_description_content_type` missing.  defaulting to `text/x-rst`.
Failed
The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line 66: Warning: Inline literal start-string without end-string.
```

I don't get these errors if I built a fresh sdist from the 4.4.0 git tag and run twine on it.

In fact if I compare the extracted contents of the 4.4.0 sdist tarball with the 4.4.0 tag from git I see a _lot_ of differences, including setup.py in the tarball reading README.md instead of README.rst!  That would explain the problem: PyPI supports Markdown, but only if you specify long_description_content_type='text/markdown'.

**Comment by micheles** [comment]
This is fixed now. The tarball for version 4.4.0 actually contained old code that was there by mistake.
