### ISSUE TITLE
Use of __file__ breaks PyOxidizer

### ISSUE THREAD

**Issue by jayvdb** [micheles/decorator#73]
It appears the use of `__file__` here is unnecessary, or could at least be `__name__ + 'py'` as a fallback.  See https://github.com/indygreg/PyOxidizer/issues/69

**Comment by micheles** [comment]
If PyOxidizer requires all modules in the world to remove the usage of ``_file_`` I see a dark future for it.
For the decorator module was actually not needed and I have removed it, but there are plenty of projects out there that will not easily remove ``__file__``, especially if the alternative requires a Python 3.7 API.

**Comment by jayvdb** [comment]
Thank you.

Each freeze project (PyInstaller, Nuitka, cx_Freeze, etc) has a bunch of hacks for handling missing `__file__`, usually with some default and then overrides for each package where the default doesnt work.  I am in the process of adding a framework for PyOxidizer which allows similar hacks for it, but I then need to copy/re-engineer each hack for each project, and then the next similar tool needs to do the same.  It is easier to fix the problem in upstream projects where it is easy to do that, as was the case here.
