### ISSUE TITLE
usage of inspect functions deprecated in Python 3.5

### ISSUE THREAD

**Issue by rgommers** [micheles/decorator#9]
``getfullargspec`` and ``formatargspec`` are used in decorator.py but will be deprecated in Python 3.5.

**Comment by micheles** [comment]
In Python 3.5b3 such functions are not yet raising a DeprecationWarning.

**Comment by rgommers** [comment]
It's a doc-only deprecation in 3.5, and will start raising a warning in 3.6 it looks like: http://bugs.python.org/issue20438

To me ``inspect.signature`` is by no means an easy-to-use direct replacement, so I can understand if you don't want to bother updating the code for this deprecation yet.
