### ISSUE TITLE
Decorator not calling at all times 

### ISSUE THREAD

**Issue by NithishReddy** [micheles/decorator#91]
class Decorator: 
    def __init__(self):
      self.x = x
      self.y = y
    def __call__(self, func): 
      def inner(*args, **kwargs):
           result = self.function(*args, **kwargs) 
           print("Exceting in Decorator")
          # after function 
          return result 
     return inner
  
 # adding class decorator to the function 
@Decorator(x=5, y =6)
def get_square(n): 
    print("Executing step1")

print in function displaying but print in decorator class is not displaying.
output: Executing step1

**Comment by Manjit2003** [comment]
I think as you defined the class name as `Decorator` and you are calling the class with `@decorator`. It seems your code breaks because of the difference in `D` and `d`
