### ISSUE TITLE
Type annotation for keyword argument in @decorator decorated functions

### ISSUE THREAD

**Issue by oliveira-mauricio** [micheles/decorator#95]
Is there some way to correctly use type annotations with @decorator decorated functions arguments?

Example:

```python
from decorator import decorator


@decorator
def my_decorator_func(_f, extra_param=None):
   # Do something with extra_param
   return _f()


@my_decorator_func(extra_param='My param')
def other_function():
   pass
```

When running mypy in this file, I get the following error:

```
(example-venv) λ mypy example.py
example.py:10: error: Unexpected keyword argument "extra_param" for "my_decorator_func"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

Using python 3.6.7, decorator 4.4.2, mypy 0.812

**Comment by micheles** [comment]
Good question. Honestly, I do not know, I do not use type annotations and last time I checked, it looked quite difficult to use them for decorators. But it was years ago, perhaps the situation has changed. If anybody knows, please post here some examples ;-)

**Comment by micheles** [comment]
The mypy documentation suggests to use overload:
https://mypy.readthedocs.io/en/latest/generics.html?highlight=decorators#decorator-factories

**Comment by beedub** [comment]
> https://mypy.readthedocs.io/en/latest/generics.html?highlight=decorators#decorator-factories

having trouble getting this to work. anyone have a basic example?
